plugins:
  - "@prettier/plugin-pug"

arrowParens: "always"
printWidth: 100
trailingComma: "all"

pugAttributeSeparator: "none"
pugCommentPreserveSpaces: "trim-all"
pugEmptyAttributes: "none"
pugClassNotation: "attribute"
