plugins:
  - "@typescript-eslint"
  - json
  - yml
  - pug

extends:
  - "plugin:@typescript-eslint/recommended"
  - "eslint:recommended"
  - "plugin:json/recommended"
  - "plugin:yml/standard"

rules:
  no-unused-vars:
    - "error"
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"

ignorePatterns:
  - "!.*"
