name: action

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/lock.json') }}

      - name: pre-download dependencies
        run: deno task cache

      - name: check lint
        run: deno task lint

      - name: check build
        run: deno task build

      - name: deploy to github pages
        if: ${{ github.ref_type == 'tag' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: public
          folder: dist

          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com

          commit-message: ${{ format('🚀 deploy {0} @ {1}@{2}', github.ref_name, github.repository, github.sha) }}
